In [4]:
#numpy refers to numerical python as refers the alias
#importing numpy library 
import numpy as np

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [7]:
#1D array
x=np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [9]:
x=np.array([45,67,5.7,60])
print(x)
print(type(x))
print(x.dtype)

[45.  67.   5.7 60. ]
<class 'numpy.ndarray'>
float64


In [13]:
x=np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)#u refers to unicode

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [17]:
x2=np.array([[20,40],[30,60]])
print(x2)
print(type(x2))
print(x2.shape)#prints the rows and columns
print(x2.dtype)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)
int32


In [23]:
a=np.array([10,20,30,40])
b=a.reshape(2,2) #possible reshapes are (2,2),(1,4),(4,1)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [26]:
a=np.array([10,20,30,40])
b=a.reshape(1,4)
print(b)
print(b.shape)

[[10 20 30 40]]
(1, 4)


In [28]:
c=np.arange(3,10)#arange function is used to create elements in a array within in a range
print(c)
print(type(c))

[3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [32]:
d=np.array([1.3467, 3.10987, 4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [35]:
d=np.array([1.3467, 3.10987, 4.91236])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.91236]
[1.16 1.76 2.22]


In [37]:
a1=np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
print(a1.dtype)

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]
float64


In [43]:
#astype is used to convert the dataypes
#arrays are immutable
a1=np.array([[3,4,5,8],[7,2,8,np.NaN]])
a1_copy=a1.astype(str)
print(a1_copy)
a1_copy.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [45]:
a2=np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [46]:
a2.sum(axis=1)#sum of row in matrix

array([13, 26, 22])

In [49]:
a2.sum(axis=0)#sum of column in matrix

array([14, 19, 28])

In [50]:
a2.mean(axis=0)#Mean of column in matrix

array([4.66666667, 6.33333333, 9.33333333])

In [51]:
a2.mean(axis=1)#Mean of row in matrix

array([4.33333333, 8.66666667, 7.33333333])

In [55]:
a3=np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)#fill_diagonal is used to make a diaginal zeros
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [57]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
c=np.matmul(A,B)
print(c)

[[19 22]
 [43 50]]


In [61]:
print(A.T)#transpose of the matrix
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [63]:
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [67]:
print(a4[2][2])#accesing the elements in the matrix by using index numbers
print(a4[2][0])

6
9


In [68]:
a4[1:3,0:2]#slicing the numbers in middle of the matrix 

array([[7, 2],
       [9, 1]])

In [70]:
a4[1:3,0:]

array([[7, 2, 8],
       [9, 1, 6]])

In [71]:
a3=np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [72]:
#print the index position of max elements
print(np.argmax(a3,axis=1))
print(np.argmax(a3,axis=0))

[2 2 0]
[2 0 1]


In [73]:
#print the max value elements
print(np.amax(a3, axis=1))
print(np.amax(a3, axis=0))

[5 8 9]
[9 4 8]
