# pandas

Pandas support series and dataframe

    Series:1D
        In series  size is immutable(cannot be changed)
    Dataframe:2D
    
Supports the indexing and slicing

Supports handling missing data with some methods

Data aggregation: includes built in functions for group operations

Data transformation: facilitates reshaping,pivoting of datasets

Time series handling

Data visualization: integrates with matplotlib for quick plotting of data

File i/o:supports reading and writing data in multiple formats

In [4]:
import pandas as pd

In [6]:
#create pandas series using list
data=[10,20,30,40]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [8]:
data=[10,20,"A",40]
series=pd.Series(data)
print(series)

0    10
1    20
2     A
3    40
dtype: object


In [11]:
#creating series using a custom index
data=[1,2,3,4]
i=['A',"B","C",'D']
series=pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [14]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_version',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'c

In [18]:
#create pandas series using dictionary
data={"a":10,"b":20,"c":30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [19]:
series.replace(20,100)

a     10
b    100
c     30
dtype: int64

In [21]:
#create series using numpy array
import numpy as np
data=np.array([100,200,300])
series=pd.Series(data,index=['a','b','c',])
print(series)

a    100
b    200
c    300
dtype: int32


# Pandas DataFrame

In [24]:
import pandas as pd
data={'Name':["varshitha","harika","pallavi"],"Age":[19,19,18],'country':["USA","UK","AUS"]}
df=pd.DataFrame(data)
print(df)

        Name  Age country
0  varshitha   19     USA
1     harika   19      UK
2    pallavi   18     AUS


In [29]:
#creating dictionary using numpy
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array, columns = ['A','B',"C"])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [33]:
#create a dataframe from a nested list
data=[[1,'Alice',25],[2,'Bob',30],[3,'Mary',34]]
print(data)

df=pd.DataFrame(data, columns=['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Mary', 34]]
   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   3   Mary   34


In [38]:
#import data from a csv file
iris_df=pd.read_csv("iris_dataset.csv")
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    

In [3]:
#import data from a csv file and create pandas
import pandas as pd
iris_df=pd.read_excel("iris - Copy.xlsx")
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    